// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-mission.tsx": () => import("../components/mockups/agent-mission.tsx"),
  "./components/mockups/agent-scanner.tsx": () => import("../components/mockups/agent-scanner.tsx"),
  "./components/mockups/booking-search.tsx": () => import("../components/mockups/booking-search.tsx"),
  "./components/mockups/company-dashboard.tsx": () => import("../components/mockups/company-dashboard.tsx"),
  "./components/mockups/company-seats.tsx": () => import("../components/mockups/company-seats.tsx"),
  "./components/mockups/passenger-list.tsx": () => import("../components/mockups/passenger-list.tsx"),
  "./components/mockups/payment.tsx": () => import("../components/mockups/payment.tsx"),
  "./components/mockups/seat-manager.tsx": () => import("../components/mockups/seat-manager.tsx"),
  "./components/mockups/ticket-scanner.tsx": () => import("../components/mockups/ticket-scanner.tsx"),
  "./components/mockups/trip-results.tsx": () => import("../components/mockups/trip-results.tsx")
};
