// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-mission.tsx": () => import("../components/mockups/agent-mission.tsx"),
  "./components/mockups/agent-scanner.tsx": () => import("../components/mockups/agent-scanner.tsx"),
  "./components/mockups/company-dashboard.tsx": () => import("../components/mockups/company-dashboard.tsx"),
  "./components/mockups/company-seats.tsx": () => import("../components/mockups/company-seats.tsx")
};
