import { db, tripsTable, seatsTable } from "@workspace/db";

const generateId = () => Date.now().toString() + Math.random().toString(36).substr(2, 9);

const CI_TRIPS = [
  // Abidjan → Bouaké
  {
    from: "Abidjan",
    to: "Bouaké",
    departureTime: "06:00",
    arrivalTime: "11:30",
    date: "2026-03-20",
    price: 4500,
    busType: "Premium",
    busName: "UTB Express",
    totalSeats: 44,
    duration: "5h 30m",
    amenities: ["AC", "WiFi", "Charging", "Snacks"],
    stops: [{ name: "Yamoussoukro", time: "08:30" }],
    policies: ["Annulation gratuite 24h avant le départ", "Billet non remboursable après 12h"],
  },
  {
    from: "Abidjan",
    to: "Bouaké",
    departureTime: "09:00",
    arrivalTime: "14:30",
    date: "2026-03-20",
    price: 3500,
    busType: "Standard",
    busName: "CTN Voyage",
    totalSeats: 50,
    duration: "5h 30m",
    amenities: ["AC", "WiFi"],
    stops: [],
    policies: ["Pas d'annulation après réservation"],
  },
  {
    from: "Abidjan",
    to: "Bouaké",
    departureTime: "14:00",
    arrivalTime: "19:30",
    date: "2026-03-20",
    price: 3500,
    busType: "Standard",
    busName: "TCV Confort",
    totalSeats: 44,
    duration: "5h 30m",
    amenities: ["AC"],
    stops: [{ name: "Tiébissou", time: "17:00" }],
    policies: ["Annulation gratuite jusqu'à 6h avant"],
  },
  {
    from: "Abidjan",
    to: "Bouaké",
    departureTime: "06:00",
    arrivalTime: "11:30",
    date: "2026-03-21",
    price: 4500,
    busType: "Premium",
    busName: "UTB Express",
    totalSeats: 44,
    duration: "5h 30m",
    amenities: ["AC", "WiFi", "Charging", "Snacks"],
    stops: [{ name: "Yamoussoukro", time: "08:30" }],
    policies: ["Annulation gratuite 24h avant le départ"],
  },
  {
    from: "Abidjan",
    to: "Bouaké",
    departureTime: "09:00",
    arrivalTime: "14:30",
    date: "2026-03-22",
    price: 3500,
    busType: "Standard",
    busName: "CTN Voyage",
    totalSeats: 50,
    duration: "5h 30m",
    amenities: ["AC", "WiFi"],
    stops: [],
    policies: ["Pas d'annulation après réservation"],
  },

  // Abidjan → Yamoussoukro
  {
    from: "Abidjan",
    to: "Yamoussoukro",
    departureTime: "07:00",
    arrivalTime: "09:30",
    date: "2026-03-20",
    price: 2500,
    busType: "Premium",
    busName: "STIF Premium",
    totalSeats: 40,
    duration: "2h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant le départ", "Changement de siège autorisé"],
  },
  {
    from: "Abidjan",
    to: "Yamoussoukro",
    departureTime: "10:00",
    arrivalTime: "12:30",
    date: "2026-03-20",
    price: 2000,
    busType: "Standard",
    busName: "Sotra Express",
    totalSeats: 50,
    duration: "2h 30m",
    amenities: ["AC"],
    stops: [],
    policies: ["Pas d'annulation"],
  },
  {
    from: "Abidjan",
    to: "Yamoussoukro",
    departureTime: "15:00",
    arrivalTime: "17:30",
    date: "2026-03-20",
    price: 2000,
    busType: "Standard",
    busName: "CTN Voyage",
    totalSeats: 44,
    duration: "2h 30m",
    amenities: ["AC", "WiFi"],
    stops: [],
    policies: ["Annulation gratuite jusqu'à 12h avant"],
  },
  {
    from: "Abidjan",
    to: "Yamoussoukro",
    departureTime: "07:00",
    arrivalTime: "09:30",
    date: "2026-03-21",
    price: 2500,
    busType: "Premium",
    busName: "STIF Premium",
    totalSeats: 40,
    duration: "2h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant le départ"],
  },
  {
    from: "Abidjan",
    to: "Yamoussoukro",
    departureTime: "10:00",
    arrivalTime: "12:30",
    date: "2026-03-22",
    price: 2000,
    busType: "Standard",
    busName: "Sotra Express",
    totalSeats: 50,
    duration: "2h 30m",
    amenities: ["AC"],
    stops: [],
    policies: ["Pas d'annulation"],
  },

  // Abidjan → Korhogo
  {
    from: "Abidjan",
    to: "Korhogo",
    departureTime: "05:00",
    arrivalTime: "14:00",
    date: "2026-03-20",
    price: 7500,
    busType: "Premium",
    busName: "UTB Grand Nord",
    totalSeats: 44,
    duration: "9h",
    amenities: ["AC", "WiFi", "Charging", "Snacks", "Blanket"],
    stops: [{ name: "Yamoussoukro", time: "07:30" }, { name: "Bouaké", time: "10:30" }],
    policies: ["Annulation gratuite 48h avant le départ", "Pas de remboursement après 24h"],
  },
  {
    from: "Abidjan",
    to: "Korhogo",
    departureTime: "06:00",
    arrivalTime: "15:00",
    date: "2026-03-20",
    price: 6000,
    busType: "Standard",
    busName: "TCV Nord Express",
    totalSeats: 50,
    duration: "9h",
    amenities: ["AC", "WiFi"],
    stops: [{ name: "Bouaké", time: "11:30" }],
    policies: ["Pas d'annulation après réservation"],
  },
  {
    from: "Abidjan",
    to: "Korhogo",
    departureTime: "05:00",
    arrivalTime: "14:00",
    date: "2026-03-21",
    price: 7500,
    busType: "Premium",
    busName: "UTB Grand Nord",
    totalSeats: 44,
    duration: "9h",
    amenities: ["AC", "WiFi", "Charging", "Snacks", "Blanket"],
    stops: [{ name: "Yamoussoukro", time: "07:30" }, { name: "Bouaké", time: "10:30" }],
    policies: ["Annulation gratuite 48h avant le départ"],
  },
  {
    from: "Abidjan",
    to: "Korhogo",
    departureTime: "06:00",
    arrivalTime: "15:00",
    date: "2026-03-22",
    price: 6000,
    busType: "Standard",
    busName: "TCV Nord Express",
    totalSeats: 50,
    duration: "9h",
    amenities: ["AC", "WiFi"],
    stops: [{ name: "Bouaké", time: "11:30" }],
    policies: ["Pas d'annulation après réservation"],
  },

  // Bouaké → Korhogo
  {
    from: "Bouaké",
    to: "Korhogo",
    departureTime: "08:00",
    arrivalTime: "11:30",
    date: "2026-03-20",
    price: 3000,
    busType: "Premium",
    busName: "UTB Liaison",
    totalSeats: 40,
    duration: "3h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant", "Échange de billet possible"],
  },
  {
    from: "Bouaké",
    to: "Korhogo",
    departureTime: "12:00",
    arrivalTime: "15:30",
    date: "2026-03-20",
    price: 2500,
    busType: "Standard",
    busName: "CTN Centre-Nord",
    totalSeats: 44,
    duration: "3h 30m",
    amenities: ["AC"],
    stops: [{ name: "Katiola", time: "13:30" }],
    policies: ["Pas d'annulation"],
  },
  {
    from: "Bouaké",
    to: "Korhogo",
    departureTime: "08:00",
    arrivalTime: "11:30",
    date: "2026-03-21",
    price: 3000,
    busType: "Premium",
    busName: "UTB Liaison",
    totalSeats: 40,
    duration: "3h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant"],
  },
  {
    from: "Bouaké",
    to: "Korhogo",
    departureTime: "12:00",
    arrivalTime: "15:30",
    date: "2026-03-22",
    price: 2500,
    busType: "Standard",
    busName: "CTN Centre-Nord",
    totalSeats: 44,
    duration: "3h 30m",
    amenities: ["AC"],
    stops: [{ name: "Katiola", time: "13:30" }],
    policies: ["Pas d'annulation"],
  },

  // Yamoussoukro → Abidjan
  {
    from: "Yamoussoukro",
    to: "Abidjan",
    departureTime: "06:00",
    arrivalTime: "08:30",
    date: "2026-03-20",
    price: 2500,
    busType: "Premium",
    busName: "STIF Premium",
    totalSeats: 40,
    duration: "2h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant le départ"],
  },
  {
    from: "Yamoussoukro",
    to: "Abidjan",
    departureTime: "10:00",
    arrivalTime: "12:30",
    date: "2026-03-20",
    price: 2000,
    busType: "Standard",
    busName: "Sotra Express",
    totalSeats: 50,
    duration: "2h 30m",
    amenities: ["AC"],
    stops: [],
    policies: ["Pas d'annulation"],
  },
  {
    from: "Yamoussoukro",
    to: "Abidjan",
    departureTime: "14:00",
    arrivalTime: "16:30",
    date: "2026-03-20",
    price: 2000,
    busType: "Standard",
    busName: "CTN Voyage",
    totalSeats: 44,
    duration: "2h 30m",
    amenities: ["AC", "WiFi"],
    stops: [],
    policies: ["Annulation gratuite jusqu'à 6h avant"],
  },
  {
    from: "Yamoussoukro",
    to: "Abidjan",
    departureTime: "06:00",
    arrivalTime: "08:30",
    date: "2026-03-21",
    price: 2500,
    busType: "Premium",
    busName: "STIF Premium",
    totalSeats: 40,
    duration: "2h 30m",
    amenities: ["AC", "WiFi", "Charging"],
    stops: [],
    policies: ["Annulation gratuite 24h avant le départ"],
  },
  {
    from: "Yamoussoukro",
    to: "Abidjan",
    departureTime: "10:00",
    arrivalTime: "12:30",
    date: "2026-03-22",
    price: 2000,
    busType: "Standard",
    busName: "Sotra Express",
    totalSeats: 50,
    duration: "2h 30m",
    amenities: ["AC"],
    stops: [],
    policies: ["Pas d'annulation"],
  },
];

async function seedCI() {
  console.log("Seeding Ivory Coast routes...");

  try {
    for (const tripData of CI_TRIPS) {
      const tripId = generateId();
      await db.insert(tripsTable).values({
        id: tripId,
        from: tripData.from,
        to: tripData.to,
        departureTime: tripData.departureTime,
        arrivalTime: tripData.arrivalTime,
        date: tripData.date,
        price: tripData.price,
        busType: tripData.busType,
        busName: tripData.busName,
        totalSeats: tripData.totalSeats,
        duration: tripData.duration,
        amenities: tripData.amenities,
        stops: tripData.stops,
        policies: tripData.policies,
      });

      // Generate seats for the trip
      const seatsPerRow = 4;
      const totalRows = Math.ceil(tripData.totalSeats / seatsPerRow);

      for (let row = 1; row <= totalRows; row++) {
        for (let col = 1; col <= 4; col++) {
          const seatNum = (row - 1) * 4 + col;
          if (seatNum > tripData.totalSeats) break;

          const seatLetter = ["A", "B", "C", "D"][col - 1];
          const type = col === 1 || col === 4 ? "window" : "aisle";
          const isBooked = Math.random() < 0.3;

          await db.insert(seatsTable).values({
            id: generateId(),
            tripId,
            number: `${row}${seatLetter}`,
            row,
            column: col,
            type,
            status: isBooked ? "booked" : "available",
            price: tripData.price,
          });

          await new Promise((r) => setTimeout(r, 1));
        }
      }

      console.log(`Seeded: ${tripData.from} → ${tripData.to} | ${tripData.busName} | ${tripData.date}`);
    }

    console.log(`\nDone! Seeded ${CI_TRIPS.length} Ivory Coast trips.`);
  } catch (err) {
    console.error("Seed error:", err);
    throw err;
  }
}

seedCI().then(() => process.exit(0)).catch((err) => {
  console.error(err);
  process.exit(1);
});
